# Generated by Django 2.2.3 on 2019-07-09 22:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('START', 'Start'), ('END', 'End')], max_length=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('call_id', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=11)),
                ('destination', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'call_record',
                'ordering': ['-id'],
            },
        ),
    ]
