# Generated by Django 2.2.3 on 2019-07-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('source', models.CharField(max_length=11)),
                ('destination', models.CharField(max_length=11)),
                ('call_start_date', models.DateField()),
                ('call_start_time', models.TimeField()),
                ('call_duration', models.CharField(max_length=20)),
                ('call_price', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
            options={
                'db_table': 'telephone_bill',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
